version: "3"

services:
  angular:
    build:
      context: .
    container_name: "dev_angular"
    command: tail -f /dev/null
    volumes:
      - ../:/home/vscode/angular
    environment:
      API_URL: http://localhost:8000
  rust:
    build:
      context: ../../api
      dockerfile: ../docker/Dockerfile-rust
    container_name: "dev_angular_rust"
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgres://recipe_admin:nbFQm5ge4NHjeXLngGPt4B3WRiUbKTNTboFvbvHqLQCDCz6q@postgres/recipe
      FRONTEND_URL: http://localhost:4200
  postgres:
    image: postgres
    container_name: "dev_angular_postgres"
    environment:
      POSTGRES_PASSWORD: nbFQm5ge4NHjeXLngGPt4B3WRiUbKTNTboFvbvHqLQCDCz6q
      POSTGRES_USER: recipe_admin
      POSTGRES_DB: recipe
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
      - ../../api/postgresql-init/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

volumes:
  postgres_data_dev:
